[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = [
  "export NODE_VERSION=22.14.0",
  "npm install --include=optional"
]

[phases.build]
cmds = [
  "export NODE_VERSION=22.14.0",
  "npm run build"
]

[start]
cmd = "npx serve dist -s -l $PORT"